import '@/styles/globals.css';

// import { GeistSans } from 'geist/font/sans';
import { Manrope } from 'next/font/google';
import { type Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';
import NextTopLoader from 'nextjs-toploader';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';

import { Providers } from '@/components/layout';
import { TRPCReactProvider } from '@/trpc/react';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
};

const inter = Manrope({
  subsets: ['latin']
});

export default async function RootLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <TRPCReactProvider>
          <Providers session={session}>
            <NextTopLoader color="hsl(var(--primary))" showSpinner={false} />
            <Toaster />
            {children}
            <Analytics />
            <SpeedInsights />
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
